spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: auto

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

memcached:
  enabled: true
  username: ${MEMCACHIER_USERNAME}
  password: ${MEMCACHIER_PASSWORD}
  servers: ${MEMCACHIER_SERVERS}
