spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

memcached:
  enabled: true
  username: ${MEMCACHIER_USERNAME}
  password: ${MEMCACHIER_PASSWORD}
  servers: ${MEMCACHIER_SERVERS}
rabbitmq:
  enabled: true
  url: ${CLOUDAMQP_URL}
  thread-pool-size: 8

wutsi:
  legacy:
    url: "http://localhost:8082"
    story:
      read-url-prefix: "${wutsi.legacy.url}/read"

