
name: master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mvn -s settings.xml install

      - name: HerokuCLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku plugins:install @heroku-cli/plugin-java

      - name: Heroku Setup
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku apps | grep wutsi-test-like-service && echo 'app: wutsi-test-like-service created' ||  heroku apps:create wutsi-test-like-service
          heroku addons -a wutsi-test-like-service | grep papertrail && echo 'addon: papertrail created' ||  heroku addons:create papertrail -a wutsi-test-like-service
          heroku addons -a wutsi-test-like-service | grep memcachier && echo 'addon: memcachier created' ||  heroku addons:create memcachier -a wutsi-test-like-service
          heroku addons -a wutsi-test-like-service | grep heroku-postgresql && echo 'addon: heroku-postgresql created' ||  heroku addons:create heroku-postgresql -a wutsi-test-like-service

      - name: Heroku Deploy
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku plugins:install @heroku-cli/plugin-java
          heroku buildpacks:clear --app wutsi-test-like-service
          heroku deploy:jar target/like-server.jar --app wutsi-test-like-service

      - name: Healthcheck
        run: |
          sleep 90
          curl -sSf https://wutsi-test-like-service.herokuapp.com/actuator/health >> /dev/null
